name: floaty_navy_bar
description: A highly customizable and dynamic floating navigation bar. Use this for your Flutter apps where you need a bottom navigation bar. To achieve the desired floaty effect, avoid passing FloatyNavyBar() to the bottomNavigationBar property. See example or README.md on how to properly use the FloatyNavyBar.
version: 1.0.0
homepage: https://github.com/mjhansen3/floaty_navy_bar.git

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
